server:
  port: 8080

spring:
  application:
    name: CARD-SERVICE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/carddb
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

  instance:
    hostname: localhost

management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: "*"
